### PR TITLE
DefenceBar player and enemy

### PR DESCRIPTION
**Pull request by shadrachbonsu**
DefenceBar has been added and working for both player and enemy

### CODE REVIEW

**Review by kalinchan — CHANGES_REQUESTED** [review]
Doesn't work. Bar value doesn't change and there is no enemy defence bar
image
(defence is zero and bar is still full)

**Comment by kalinchan** [comment]
Also, end turn button disappears once you have ended turn (not sure if your changes are the cause)

**Comment by shadrachbonsu** [comment]
It looks when developing the defence bar for both player and enemy. it looks like the latest update did not apply. As a lot of code is missing which I do not understand why. Probably due to my laptop policy blocking some updates which are strange. 

Redeveloping the defence bar again on a personal computer.

Can this pull request be cancelled, please

**Comment by shadrachbonsu** [comment]
The defence bar for player and enemy has been rebuilt and has all code for it to work. fixed the end turn issue. This is due to an error with the defence bar code but has been removed and rewritten. Can this be reviewed?

**Comment by chelseahouston** [comment]
> Also, end turn button disappears once you have ended turn (not sure if your changes are the cause)

This is normal behaviour, it disappears during enemy turn and reappears when it's player turn.

**Pull request closed without merging**
